services:
  app:
    image: 'git.toast-server.net/toast/agriview:latest'
    environment:
      FS_IP: ''
      FS_MD5: ''
    networks:
      - traefik-pub
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - traefik.http.routers.agriview_main.rule=Host(``)
        - traefik.http.routers.agriview_local.rule=Host(``)
        - traefik.http.services.agriview.loadbalancer.server.port=3030

networks:
  traefik-pub:
    external: true
